export const TRAINLAB_DEVICES = {
  id: "trainlab-devices",
  brand: "TRAIN LAB",
  items: [
    {
      id: 1,
      name: "ЭС PODONKI 6000 ТЯГ",
      goods: [
        { id: 1, image: false, name: "АНАНАС КОКОС" },
        { id: 2, image: false, name: "АПЕЛЬСИН" },
        { id: 3, image: false, name: "АРБУЗ КЛУБНИКА" },
        { id: 4, image: false, name: "ВИНОГРАД" },
        { id: 5, image: false, name: "КЛУБНИКА ЛИЧИ" },
        { id: 6, image: false, name: "КОЛА" },
        { id: 7, image: false, name: "МАНГО ПЕРСИК" },
        { id: 8, image: false, name: "МОЛОЧНО-БАНАНОВЫЙ ШЕЙК" },
        { id: 9, image: false, name: "МОЛОЧНЫЙ ЧАЙ" },
        { id: 10, image: false, name: "ФРУКТОВЫЙ МИКС" },
        { id: 11, image: false, name: "ЧЕРЕШНЯ ЧЕРНИКА" },
        { id: 12, image: false, name: "ЧЕРНИКА МАЛИНА" },
        { id: 13, image: false, name: "ШОКОЛАДНОЕ МОЛОКО" },
        { id: 14, image: false, name: "ЭНЕРГЕТИК" },
      ],
    },
    {
      id: 2,
      name: "ЭС PODONKI 10000 ТЯГ",
      goods: [
        { id: 1, image: false, name: "АНАНАСОВОЕ КОКОСОВОЕ МОЛОКО" },
        { id: 2, image: false, name: "ВИШНЕВО-БАНАНОВЫЙ ЛЕД" },
        { id: 3, image: false, name: "ВИШНЯ ЧЕРНИКА" },
        { id: 4, image: false, name: "КИВИ ГУАВА МАРАКУЙЯ" },
        { id: 5, image: false, name: "КИВИ ЯБЛОКО РЭДБУЛ" },
        { id: 6, image: false, name: "КЛУБНИКА КИВИ" },
        { id: 7, image: false, name: "КЛУБНИКА КОКОС" },
        { id: 8, image: false, name: "КЛУБНИЧНОЕ МОРОЖЕНОЕ" },
        { id: 9, image: false, name: "ЛЕДЯНАЯ ЧЕРНИКА" },
        { id: 10, image: false, name: "ЛЕДЯНОЕ МАНГО" },
        { id: 11, image: false, name: "ЛЕДЯНОЙ АРБУЗ" },
        { id: 12, image: false, name: "ЛЕДЯНОЙ ВИНОГРАД" },
        { id: 13, image: false, name: "МАРАКУЙЯ МАНГО" },
        { id: 14, image: false, name: "МАРМЕЛАДНЫЕ МИШКИ" },
        { id: 15, image: false, name: "МЕДОВЫЙ ПЕРСИК АПЕЛЬСИН" },
        { id: 16, image: false, name: "ТРОПИЧЕСКИЕ ФРУКТЫ" },
        { id: 17, image: false, name: "ФАНТА КОЛА СО ЛЬДОМ" },
        { id: 18, image: false, name: "ЧЕРНИЧНО-ВИШНЕВЫЙ СОК" },
        { id: 19, image: false, name: "ЧЕРНИЧНО-МАЛИНОВЫЙ ЛИМОНАД" },
        { id: 20, image: false, name: "ЯПОНСКИЙ ЧАЙ" },
      ],
    },
    {
      id: 3,
      name: "ЭСДН PODONKI 7000 ТЯГ",
      goods: [
        { id: 1, image: false, name: "СОЧНЫЙ АПЕЛЬСИН ТРОПИК" },
        { id: 2, image: false, name: "СЛАДКИЙ ВИШНЕВЫЙ ВИНОГРАД" },
        { id: 3, image: false, name: "ДВОЙНОЙ КИВИ КЛУБНИКА" },
        { id: 4, image: false, name: "ИЗЫСКАННЫЙ КЛУБНИЧНЫЙ ЙОГУРТ" },
        { id: 5, image: false, name: "СОЛЕНЫЙ ЛИМОН ДЛЯ ТЕКИЛЫ" },
        { id: 6, image: false, name: "ХОЛОДНОЕ ЛИМОННОЕ МОРОЖЕНОЕ" },
        { id: 7, image: false, name: "НЕЖНЫЙ МАЛИНОВЫЙ МИЛКШЕЙК С РОЗОЙ" },
        { id: 8, image: false, name: "ЛЮБИМЫЙ МАРМЕЛАДНЫЙ МИШКА" },
        { id: 9, image: false, name: "ТЯГУЧАЯ НУГА" },
        { id: 10, image: false, name: "КИСЛЫЙ СКИТЛС" },
        { id: 11, image: false, name: "ЭКЗОТИЧЕСКИЙ ТРОЙНОЙ МАНГО" },
        { id: 12, image: false, name: "БАРХАТНЫЙ ТУТОВЫЙ ВИНОГРАД" },
        { id: 13, image: false, name: "ЧЕРНЫЙ ЧЕРНОСМОРОДИНОВЫЙ МИЛКШЕЙК" },
        { id: 14, image: false, name: "СТАНДАРТНЫЙ ЯБЛОКО АПЕЛЬСИН" },
        { id: 15, image: false, name: "СТРОГИЙ ЯБЛОЧНЫЙ ТАБАК" },
      ],
    },
    {
      id: 4,
      name: "ЭСДН PODONKI & MALASIAN 12000 ТЯГ",
      goods: [
        { id: 1, image: false, name: "ДВОЙНОЕ ЯБЛОКО" },
        { id: 2, image: false, name: "КЛУБНИКА КИВИ" },
        { id: 3, image: false, name: "ЛИМОН ЛАЙМ" },
        { id: 4, image: false, name: "МАЛИНОВЫЙ МАРМЕЛАД" },
        { id: 5, image: false, name: "МАРАКУЙЯ АПЕЛЬСИН" },
        { id: 6, image: false, name: "ПЕРСИКОВЫЙ БАБЛГАМ" },
        { id: 7, image: false, name: "СЛАДКАЯ ВАТА" },
        { id: 8, image: false, name: "ХОЛОДНАЯ ВИШНЯ" },
        { id: 9, image: false, name: "ХОЛОДНАЯ ЕЖЕВИКА" },
        { id: 10, image: false, name: "ХОЛОДНАЯ КЛУБНИКА" },
        { id: 11, image: false, name: "ХОЛОДНАЯ СМОРОДИНА" },
        { id: 12, image: false, name: "ХОЛОДНАЯ ЧЕРНИКА" },
        { id: 13, image: false, name: "ХОЛОДНЫЙ ВИНОГРАД" },
        { id: 14, image: false, name: "ХОЛОДНЫЙ МАНГО" },
        { id: 15, image: false, name: "ЭНЕРГЕТИК" },
      ],
    },
  ],
};
