import {
  trainlabPodonkiAnarchyBlackcurrantLemonade,
  trainlabPodonkiAnarchyBlueberryCheesecake,
  trainlabPodonkiAnarchyCranberrySoda,
  trainlabPodonkiAnarchyGrapesIce,
  trainlabPodonkiAnarchyLemonadeIce,
  trainlabPodonkiAnarchyMangoIce,
  trainlabPodonkiAnarchyOrangeJuiceWithIce,
  trainlabPodonkiAnarchyPineappleIce,
  trainlabPodonkiAnarchyRaspberryLychee,
  trainlabPodonkiAnarchyTarragonLemon,
  trainlabPodonkiLastHapkaBlaze,
  trainlabPodonkiLastHapkaBloodyValentines,
  trainlabPodonkiLastHapkaBornThisWay,
  trainlabPodonkiLastHapkaCrashTest,
  trainlabPodonkiLastHapkaHighVoltage,
  trainlabPodonkiLastHapkaInsertHere,
  trainlabPodonkiLastHapkaKindALonely,
  trainlabPodonkiLastHapkaMadnessWeek,
  trainlabPodonkiLastHapkaOnHold,
  trainlabPodonkiLastHapkaPoorPot,
  trainlabPodonkiLastHapkaSlavesSlayer,
  trainlabPodonkiLastHapkaSpaceControl,
  trainlabPodonkiLastHapkaTheEndOfOwnership,
  trainlabPodonkiLastHapkaWatchPot,
  trainlabPodonkiLastHapkaYouAreMyDessert,
  trainlabPodonkiV1ApricotGum,
  trainlabPodonkiV1BananaStrawberryIce,
  trainlabPodonkiV1CherryApple,
  trainlabPodonkiV1CherryLimeIce,
  trainlabPodonkiV1ClassicColaWithIce,
  trainlabPodonkiV1CranberriesCranberriesRaspberries,
  trainlabPodonkiV1CurrantHalls,
  trainlabPodonkiV1CurrantLemonade,
  trainlabPodonkiV1DoubleAppleIce,
  trainlabPodonkiV1IcedLycheeGrapeMint,
  trainlabPodonkiV1NeedlesWildBerries,
  trainlabPodonkiV1RaspberryAndStrawberryGum,
  trainlabPodonkiV1RaspberryCherry,
  trainlabPodonkiV1RaspberryLemonade,
  trainlabPodonkiV1TropicalFruitsWithIce,
  trainlabPodonkiV1WildBerriesWithIce,
  trainlabPodonkiV2BananaMilk,
  trainlabPodonkiV2CurrantHalls,
  trainlabPodonkiV2GrapeCactusGum,
  trainlabPodonkiV2PineappleEnergyDrink,
  trainlabPodonkiV2StrawberriesWithChampagne,
  trainlabPodonkiV2StrawberryIceCream,
  trainlabPodonkiV2TarragonWithKiwiAndLime,
  trainlabPodonkiV2WatermelonIceCream,
} from "..";

export const TRAINLAB_LINES = {
  id: "trainlab-lines",
  brand: "TRAIN LAB",
  items: [
    {
      id: 1,
      name: "PODONKI LAST HAP'KA",
      goods: [
        { id: 1, image: trainlabPodonkiLastHapkaBlaze, name: "BLAZE" },
        {
          id: 2,
          image: trainlabPodonkiLastHapkaBloodyValentines,
          name: "BLOODY VALENTINE'S",
        },
        {
          id: 3,
          image: trainlabPodonkiLastHapkaBornThisWay,
          name: "BORN THIS WAY",
        },
        {
          id: 4,
          image: trainlabPodonkiLastHapkaCrashTest,
          name: "CRASH TEST",
        },
        {
          id: 5,
          image: trainlabPodonkiLastHapkaHighVoltage,
          name: "HIGH VOLTAGE",
        },
        {
          id: 6,
          image: trainlabPodonkiLastHapkaInsertHere,
          name: "INSERT HERE",
        },
        {
          id: 7,
          image: trainlabPodonkiLastHapkaKindALonely,
          name: "KIND A LONELY",
        },
        {
          id: 8,
          image: trainlabPodonkiLastHapkaMadnessWeek,
          name: "MADNESS WEEK",
        },
        {
          id: 9,
          image: trainlabPodonkiLastHapkaOnHold,
          name: "ON HOLD",
        },
        {
          id: 10,
          image: trainlabPodonkiLastHapkaPoorPot,
          name: "POOR",
        },
        {
          id: 11,
          image: trainlabPodonkiLastHapkaSlavesSlayer,
          name: "SLAVES SLAYER",
        },
        {
          id: 12,
          image: trainlabPodonkiLastHapkaSpaceControl,
          name: "SPACE CONTROL",
        },
        {
          id: 13,
          image: trainlabPodonkiLastHapkaTheEndOfOwnership,
          name: "THE END OF OWNERSHIP",
        },
        {
          id: 14,
          image: trainlabPodonkiLastHapkaWatchPot,
          name: "WATCH",
        },
        {
          id: 15,
          image: trainlabPodonkiLastHapkaYouAreMyDessert,
          name: "YOU'RE MY DESSERT",
        },
      ],
    },
    {
      id: 2,
      name: "PODONKI VINTAGE",
      goods: [
        { id: 1, image: false, name: "АПЕЛЬСИНОВАЯ ГАЗИРОВКА" },
        { id: 2, image: false, name: "БРУСНИЧНЫЙ МОРС" },
        { id: 3, image: false, name: "ВИНОГРАДНАЯ ГАЗИРОВКА" },
        { id: 4, image: false, name: "ЕЖЕВИЧНЫЙ ЛИМОНАД" },
        { id: 5, image: false, name: "КЛУБНИЧНЫЙ МОХИТО" },
        { id: 6, image: false, name: "ЗЕМЛЯНИЧНЫЙ МУСС" },
        { id: 7, image: false, name: "КЛЮКВЕННАЯ ГАЗИРОВКА" },
        { id: 8, image: false, name: "МАЛИНОВЫЙ ПУНШ" },
        { id: 9, image: false, name: "МАРМЕЛАДНЫЙ ДЖИН" },
        { id: 10, image: false, name: "МОРС ЧЕРНИКА ВИНОГРАД" },
        { id: 11, image: false, name: "ОСВЕЖАЮЩИЙ ЛИМОНАД" },
        { id: 12, image: false, name: "ПИНА КОЛАДА С ГРУШЕЙ" },
        { id: 13, image: false, name: "СМОРОДИНОВЫЙ ЛИМОНАД" },
        { id: 14, image: false, name: "ЮППИ-АНАНАС СО ЛЬДОМ" },
        { id: 15, image: false, name: "ЯБЛОЧНЫЙ ЛИМОНАД" },
      ],
    },
    {
      id: 3,
      name: "PODONKI V1",
      goods: [
        {
          id: 1,
          image: trainlabPodonkiV1ApricotGum,
          name: "ЖВАЧКА АБРИКОС",
        },
        {
          id: 2,
          image: trainlabPodonkiV1BananaStrawberryIce,
          name: "БАНАН КЛУБНИКА ЛЁД",
        },
        {
          id: 3,
          image: trainlabPodonkiV1CherryApple,
          name: "ВИШНЯ ЯБЛОКО",
        },
        {
          id: 4,
          image: trainlabPodonkiV1CherryLimeIce,
          name: "ВИШНЯ ЛАЙМ ЛЁД",
        },
        {
          id: 5,
          image: trainlabPodonkiV1ClassicColaWithIce,
          name: "КЛАССИЧЕСКАЯ КОЛА СО ЛЬДОМ",
        },
        {
          id: 6,
          image: trainlabPodonkiV1CranberriesCranberriesRaspberries,
          name: "БРУСНИКА КЛЮКВА МАЛИНА",
        },
        {
          id: 7,
          image: trainlabPodonkiV1CurrantHalls,
          name: "СМОРОДИНОВЫЙ ХОЛС",
        },
        {
          id: 8,
          image: trainlabPodonkiV1CurrantLemonade,
          name: "СМОРОДИНОВЫЙ ЛИМОНАД",
        },
        {
          id: 9,
          image: trainlabPodonkiV1DoubleAppleIce,
          name: "ДВОЙНОЕ ЯБЛОКО ЛЁД",
        },
        {
          id: 10,
          image: trainlabPodonkiV1IcedLycheeGrapeMint,
          name: "ЛЕДЯНОЙ ЛИЧИ ВИНОГРАД МЯТА",
        },
        {
          id: 11,
          image: trainlabPodonkiV1NeedlesWildBerries,
          name: "ХВОЯ ЛЕСНЫЕ ЯГОДЫ",
        },
        {
          id: 12,
          image: trainlabPodonkiV1RaspberryAndStrawberryGum,
          name: "МАЛИНОВО-КЛУБНИЧНАЯ ЖВАЧКА",
        },
        {
          id: 13,
          image: trainlabPodonkiV1RaspberryCherry,
          name: "МАЛИНА ВИШНЯ",
        },
        {
          id: 14,
          image: trainlabPodonkiV1RaspberryLemonade,
          name: "МАЛИНОВЫЙ ЛИМОНАД",
        },
        {
          id: 15,
          image: trainlabPodonkiV1TropicalFruitsWithIce,
          name: "ТРОПИЧЕСКИЕ ФРУКТЫ СО ЛЬДОМ",
        },
        {
          id: 16,
          image: trainlabPodonkiV1WildBerriesWithIce,
          name: "ЛЕСНЫЕ ЯГОДЫ СО ЛЬДОМ",
        },
      ],
    },
    {
      id: 4,
      name: "PODONKI АНАРХИЯ",
      goods: [
        {
          id: 1,
          image: trainlabPodonkiAnarchyBlackcurrantLemonade,
          name: "ЧЕРНОСМОРОДИНОВЫЙ ЛИМОНАД",
        },
        {
          id: 2,
          image: trainlabPodonkiAnarchyBlueberryCheesecake,
          name: "ЧИЗКЕЙК С ГОЛУБИКОЙ",
        },
        {
          id: 3,
          image: trainlabPodonkiAnarchyCranberrySoda,
          name: "КЛЮКВЕННАЯ СОДОВАЯ",
        },
        {
          id: 4,
          image: trainlabPodonkiAnarchyGrapesIce,
          name: "ВИНОГРАД АЙС",
        },
        {
          id: 5,
          image: trainlabPodonkiAnarchyLemonadeIce,
          name: "ЛИМОНАД АЙС",
        },
        {
          id: 6,
          image: trainlabPodonkiAnarchyMangoIce,
          name: "МАНГО АЙС",
        },
        {
          id: 7,
          image: trainlabPodonkiAnarchyOrangeJuiceWithIce,
          name: "АПЕЛЬСИНОВЫЙ СОК СО ЛЬДОМ",
        },
        {
          id: 8,
          image: trainlabPodonkiAnarchyPineappleIce,
          name: "АНАНАС АЙС",
        },
        {
          id: 9,
          image: trainlabPodonkiAnarchyRaspberryLychee,
          name: "МАЛИНА ЛИЧИ",
        },
        {
          id: 10,
          image: trainlabPodonkiAnarchyTarragonLemon,
          name: "ТАРХУН ЛИМОН",
        },
      ],
    },
    {
      id: 5,
      name: "PODONKI V2",
      goods: [
        {
          id: 1,
          image: trainlabPodonkiV2BananaMilk,
          name: "БАНАНОВОЕ МОЛОКО",
        },
        {
          id: 2,
          image: trainlabPodonkiV2CurrantHalls,
          name: "СМОРОДИНОВЫЙ ХОЛС",
        },
        {
          id: 3,
          image: trainlabPodonkiV2GrapeCactusGum,
          name: "ВИНОГРАДНО КАКТУСОВАЯ ЖВАЧКА",
        },
        {
          id: 4,
          image: trainlabPodonkiV2PineappleEnergyDrink,
          name: "АНАНАСОВЫЙ ЭНЕРГЕТИК",
        },
        {
          id: 5,
          image: trainlabPodonkiV2StrawberriesWithChampagne,
          name: "КЛУБНИКА С ШАМПАНСКИМ",
        },
        {
          id: 6,
          image: trainlabPodonkiV2StrawberryIceCream,
          name: "КЛУБНИЧНОЕ МОРОЖЕНОЕ",
        },
        {
          id: 7,
          image: trainlabPodonkiV2TarragonWithKiwiAndLime,
          name: "ТАРХУН С КИВИ И ЛАЙМОМ",
        },
        {
          id: 8,
          image: trainlabPodonkiV2WatermelonIceCream,
          name: "АРБУЗНОЕ МОРОЖЕНОЕ",
        },
      ],
    },
    {
      id: 6,
      name: "PODONKI & XYLINET",
      goods: [
        { id: 1, image: false, name: "АНАНАС КЛУБНИКА АЙС" },
        { id: 2, image: false, name: "АРБУЗНАЯ КОНФЕТА" },
        { id: 3, image: false, name: "БАБЛ ГАМ" },
        { id: 4, image: false, name: "БАНАН КАРАМЕЛЬ" },
        { id: 5, image: false, name: "ВИНОГРАДНЫЙ ЛЕД" },
        { id: 6, image: false, name: "ВИШНЕВЫЙ ФРЕШ АЙС" },
        { id: 7, image: false, name: "ГРЕЙПБЕРРИ ФЬЮЖН АЙС" },
        { id: 8, image: false, name: "ГРЕЙПФРУТОВЫЙ ЭНЕРГЕТИК" },
        { id: 9, image: false, name: "КЛУБНИЧНЫЙ МУСС АЙС" },
        { id: 10, image: false, name: "КОКОСОВЫЙ ПУНШ АЙС" },
        { id: 11, image: false, name: "МАЛИНА ЛИЧИ АЙС" },
        { id: 12, image: false, name: "МАНГО ПЕРСИК АЙС" },
        { id: 13, image: false, name: "МЯТНАЯ ЖВАЧКА" },
        { id: 14, image: false, name: "ЧЕРНИЧНЫЙ ЙОГУРТ" },
        { id: 15, image: false, name: "ЯГОДНЫЙ МИКС" },
      ],
    },
    {
      id: 7,
      name: "PODONKI & MALASIAN",
      goods: [
        { id: 1, image: false, name: "ВИНОГРАД КЛУБНИКА" },
        { id: 2, image: false, name: "ВИШНЯ АНАНАС" },
        { id: 3, image: false, name: "ЖВАЧКА КЛУБНИКА КИВИ" },
        {
          id: 4,
          image: false,
          name: "МАЛИНА КЛУБНИКА ЧЕРНАЯ И КРАСНАЯ СМОРОДИНА",
        },
        { id: 5, image: false, name: "МАНГО ГУАВА МАРАКУЙЯ" },
        { id: 6, image: false, name: "МАРАКУЙЯ ГУАВА АПЕЛЬСИН" },
        {
          id: 7,
          image: false,
          name: "МАРМЕЛАДНЫЕ МИШКИ С МАНДАРИНОМ И ЛИМОНОМ",
        },
        { id: 8, image: false, name: "РОЗОВЫЙ ЛИМОНАД МАЛИНА ЛИМОН" },
        { id: 9, image: false, name: "ЧЕРНАЯ СМОРОДИНА МАЛИНА АНИС МЕНТОЛ" },
      ],
    },
    {
      id: 8,
      name: "PODONKI ANGRY VAPE",
      goods: [
        { id: 1, image: false, name: "АНАНАС И КЛУБНИКА СО ЛЬДОМ" },
        { id: 2, image: false, name: "ВИШНЯ С ЛИМОНОМ" },
        { id: 3, image: false, name: "ГРЕЙПФРУТОВЫЙ ЛИМОНАД" },
        { id: 4, image: false, name: "КИВИ И ЯБЛОКО СО ЛЬДОМ" },
        { id: 5, image: false, name: "КЛУБНИКА С БАНАНОМ, МАРАКУЙЕЙ И МЯТОЙ" },
        { id: 6, image: false, name: "ЛИМОН И ЛАЙМ С МЯТОЙ" },
        { id: 7, image: false, name: "ЛИМОННЫЙ ДЖЕМ" },
        { id: 8, image: false, name: "МАЛИНА И ГРЕЙПФРУТ СО ЛЬДОМ" },
        { id: 9, image: false, name: "СМОРОДИНА И ВИШНЯ СО ЛЬДОМ" },
        { id: 10, image: false, name: "ФРЕШ С ФЕЙХОА, ЛИМОНОМ И МЯТОЙ" },
        { id: 11, image: false, name: "ЦИТРУСОВЫЙ СМУЗИ" },
        { id: 12, image: false, name: "ЧЕРНАЯ СМОРОДИНА И ЛИМОН СО ЛЬДОМ" },
        { id: 13, image: false, name: "ЯБЛОЧНАЯ ЖВАЧКА" },
      ],
    },
  ],
};
