import {
  vliq30mlBlizzardApple,
  vliq30mlBlizzardCherry,
  vliq30mlBlizzardCranberries,
  vliq30mlBlizzardCurrant,
  vliq30mlBlizzardEnergyDrink,
  vliq30mlBlizzardKiwi,
  vliq30mlBlizzardLemonPie,
  vliq30mlBlizzardLychee,
  vliq30mlBlizzardMango,
  vliq30mlBlizzardMarmalade,
  vliq30mlBlizzardMountainDew,
  vliq30mlBlizzardPineappleLemon,
  vliq30mlBlizzardRaspberry,
  vliq30mlBlizzardSkittels,
  vliq30mlBlizzardStrawberry,
  vliq30mlFataMorganaBanana,
  vliq30mlFataMorganaCurrant,
  vliq30mlFataMorganaFanta,
  vliq30mlFataMorganaLycheeStrawberry,
  vliq30mlFataMorganaMangoGuava,
  vliq30mlFataMorganaOrbitLime,
  vliq30mlFataMorganaPeachCinnabon,
  vliq30mlFataMorganaRaspberry,
  vliq30mlFataMorganaStrawberryLiqurcie,
  vliq30mlFataMorganaStrawberryTea,
  vliq30mlFranklyMonkeyBlackBlueberryJam,
  vliq30mlFranklyMonkeyBlackBubbleGum,
  vliq30mlFranklyMonkeyBlackCurrant,
  vliq30mlFranklyMonkeyBlackGrapeIceCream,
  vliq30mlFranklyMonkeyBlackMultifruit,
  vliq30mlFranklyMonkeyBlackNuts,
  vliq30mlFranklyMonkeyBlackRaspberryLemon,
  vliq30mlFranklyMonkeyBlackStrawberryKiwi,
  vliq30mlFranklyMonkeyMetaUniverseBarberry,
  vliq30mlFranklyMonkeyMetaUniverseBlueberryPorridge,
  vliq30mlFranklyMonkeyMetaUniverseCactus,
  vliq30mlFranklyMonkeyMetaUniverseDelicateYogurt,
  vliq30mlFranklyMonkeyMetaUniverseFeijoa,
  vliq30mlFranklyMonkeyMetaUniverseFruitMix,
  vliq30mlFranklyMonkeyMetaUniverseIceApple,
  vliq30mlFranklyMonkeyMetaUniverseIceStrawberry,
  vliq30mlFranklyMonkeyMetaUniverseMango,
  vliq30mlFranklyMonkeyMetaUniverseSaltedCaramel,
  vliq30mlFranklyMonkeyMetaUniverseShoria,
  vliq30mlFranklyMonkeyMetaUniverseStrawberryCheescake,
  vliq30mlFranklyMonkeyMetaUniverseStrawberryKiwi,
  vliq30mlFranklyMonkeyMetaUniverseStrawberryRaf,
  vliq30mlFreezeBreezeBerryMix,
  vliq30mlFreezeBreezeBlackHole,
  vliq30mlFreezeBreezeBlueberry,
  vliq30mlFreezeBreezeCherryJuice,
  vliq30mlFreezeBreezeCitrusPunch,
  vliq30mlFreezeBreezeCola,
  vliq30mlFreezeBreezeFanta,
  vliq30mlFreezeBreezeGrapeJuice,
  vliq30mlFreezeBreezeKiwiApple,
  vliq30mlFreezeBreezeKiwiGrapefruit,
  vliq30mlFreezeBreezeLycheePineapple,
  vliq30mlFreezeBreezeMangoOrange,
  vliq30mlFreezeBreezeMangoPassionFruit,
  vliq30mlFreezeBreezePeachApple,
  vliq30mlFreezeBreezePeachStrawberrySmoothe,
  vliq30mlFreezeBreezePineappleJuice,
  vliq30mlFreezeBreezeRaspberryPear,
  vliq30mlFreezeBreezeRootBeer,
  vliq30mlFreezeBreezeShockApple,
  vliq30mlFreezeBreezeShockCherry,
  vliq30mlFreezeBreezeShockCranberries,
  vliq30mlFreezeBreezeShockCurrant,
  vliq30mlFreezeBreezeShockEnergyDrink,
  vliq30mlFreezeBreezeShockKiwi,
  vliq30mlFreezeBreezeShockLemonPie,
  vliq30mlFreezeBreezeShockLychee,
  vliq30mlFreezeBreezeShockMango,
  vliq30mlFreezeBreezeShockMarmalade,
  vliq30mlFreezeBreezeShockMountainDew,
  vliq30mlFreezeBreezeShockPineappleLemon,
  vliq30mlFreezeBreezeShockRaspberry,
  vliq30mlFreezeBreezeShockSkittels,
  vliq30mlFreezeBreezeShockStrawberry,
  vliq30mlFreezeBreezeTropicalExplosion,
  vliq30mlFreezeBreezeWildBerries,
  vliq30mlFrostDrozdBlackberry,
  vliq30mlFrostDrozdBlueberry,
  vliq30mlFrostDrozdCactus,
  vliq30mlFrostDrozdCoconutPassionPineapple,
  vliq30mlFrostDrozdDragonFruit,
  vliq30mlFrostDrozdGuavaLychee,
  vliq30mlFrostDrozdKiwiGrape,
  vliq30mlFrostDrozdLemon,
  vliq30mlFrostDrozdMango,
  vliq30mlFrostDrozdMangoPassionSoda,
  vliq30mlFrostDrozdMelonApple,
  vliq30mlFrostDrozdPear,
  vliq30mlFrostDrozdPineappleSoda,
  vliq30mlFrostDrozdPinkman,
  vliq30mlFrostDrozdSherbet,
  vliq30mlFrostDrozdStrawberryPineapple,
  vliq30mlFrostDrozdTuttiFruti,
  vliq30mlFrostDrozdWatermelon,
  vliq30mlHolodnoPesecApple,
  vliq30mlHolodnoPesecBlueberries,
  vliq30mlHolodnoPesecCherry,
  vliq30mlHolodnoPesecCurrantPear,
  vliq30mlHolodnoPesecDrPepper,
  vliq30mlHolodnoPesecEnergyDrinkKiwi,
  vliq30mlHolodnoPesecGrape,
  vliq30mlHolodnoPesecGreenMango,
  vliq30mlHolodnoPesecOrange,
  vliq30mlHolodnoPesecPassionFruit,
  vliq30mlHolodnoPesecPeach,
  vliq30mlHolodnoPesecPineapple,
  vliq30mlHolodnoPesecRaspberry,
  vliq30mlHolodnoPesecSpriteWithCucumber,
  vliq30mlHolodnoPesecWildStrawberry,
  vliq30mlLootCherryYogurt,
  vliq30mlLootCinnamonApple,
  vliq30mlLootCrazyWatermelon,
  vliq30mlLootCurrantRaspberry,
  vliq30mlLootFejioa,
  vliq30mlLootFunnyRaspberry,
  vliq30mlLootIceAmazingMojito,
  vliq30mlLootIceCitrusFruit,
  vliq30mlLootIceGreenApple,
  vliq30mlLootIceKiwiMango,
  vliq30mlLootIceLimeCactus,
  vliq30mlLootIceMangoApple,
  vliq30mlLootIceMelissa,
  vliq30mlLootIceOrangePassion,
  vliq30mlLootIcePeachPassion,
  vliq30mlLootIcePineappleLychee,
  vliq30mlLootIceRareBerries,
  vliq30mlLootIceStrawberryCherry,
  vliq30mlLootIceStrawberryLemon,
  vliq30mlLootIceWatermelonMandarin,
  vliq30mlLootKiwi,
  vliq30mlLootLimeApple,
  vliq30mlLootPear,
  vliq30mlLootPomegranateApple,
  vliq30mlLootRareTropics,
  vliq30mlLootStrawberry,
  vliq30mlLootSuperPunch,
  vliq30mlMaxFlavorAperol,
  vliq30mlMaxFlavorApple,
  vliq30mlMaxFlavorApplePear,
  vliq30mlMaxFlavorBerriesWithMint,
  vliq30mlMaxFlavorBerryYogurt,
  vliq30mlMaxFlavorBlueRaspberry,
  vliq30mlMaxFlavorCactus,
  vliq30mlMaxFlavorCarrot,
  vliq30mlMaxFlavorEnergyDrinkWithMango,
  vliq30mlMaxFlavorGrapeWithAloe,
  vliq30mlMaxFlavorGuava,
  vliq30mlMaxFlavorKiwi,
  vliq30mlMaxFlavorLemonadeStrawberryBasil,
  vliq30mlMaxFlavorLemonRaspberry,
  vliq30mlMaxFlavorLycheeWithTropicalFruits,
  vliq30mlMaxFlavorMarmalade,
  vliq30mlMaxFlavorMelon,
  vliq30mlMaxFlavorMintTickTock,
  vliq30mlMaxFlavorPeach,
  vliq30mlMaxFlavorPear,
  vliq30mlMaxFlavorPinaColada,
  vliq30mlMaxFlavorPineapple,
  vliq30mlMaxFlavorRoseWithJasmine,
  vliq30mlMaxFlavorStrawberry,
  vliq30mlMaxFlavorStrawberryBanana,
  vliq30mlMaxFlavorStrawberryLemonMango,
  vliq30mlMaxFlavorStrawberryPineappleLemongrass,
  vliq30mlMaxFlavorSweetGrapefruit,
  vliq30mlMaxFlavorWatermelonLemonade,
  vliq30mlMaxFlavorYellowMangoWithRaspberries,
  vliq120mlBlizzardApple,
  vliq120mlBlizzardCherry,
  vliq120mlBlizzardCranberries,
  vliq120mlBlizzardCurrant,
  vliq120mlBlizzardEnergyDrink,
  vliq120mlBlizzardKiwi,
  vliq120mlBlizzardLemonPie,
  vliq120mlBlizzardLychee,
  vliq120mlBlizzardMango,
  vliq120mlBlizzardMarmalade,
  vliq120mlBlizzardMountainDew,
  vliq120mlBlizzardPineappleLemon,
  vliq120mlBlizzardRasberry,
  vliq120mlBlizzardSkittels,
  vliq120mlBlizzardStrawberry,
  vliq120mlFataMorganaBanana,
  vliq120mlFataMorganaCurrant,
  vliq120mlFataMorganaFanta,
  vliq120mlFataMorganaLycheeStrawberry,
  vliq120mlFataMorganaMangoGuava,
  vliq120mlFataMorganaOrbitLime,
  vliq120mlFataMorganaPeachCinnamon,
  vliq120mlFataMorganaRaspberry,
  vliq120mlFataMorganaStrawberryLiquorice,
  vliq120mlFataMorganaStrawberryTea,
  vliq120mlFranklyMonkeyBlackBlueberryJam,
  vliq120mlFranklyMonkeyBlackBubbleGum,
  vliq120mlFranklyMonkeyBlackCrapeIceCream,
  vliq120mlFranklyMonkeyBlackCurrant,
  vliq120mlFranklyMonkeyBlackKiwiStrawberry,
  vliq120mlFranklyMonkeyBlackMultifruit,
  vliq120mlFranklyMonkeyBlackNuts,
  vliq120mlFranklyMonkeyBlackRaspberryLemon,
  vliq120mlFranklyMonkeyMetaUniverseBarberry,
  vliq120mlFranklyMonkeyMetaUniverseBlueberryPorrige,
  vliq120mlFranklyMonkeyMetaUniverseCactus,
  vliq120mlFranklyMonkeyMetaUniverseDelicateYogurt,
  vliq120mlFranklyMonkeyMetaUniverseFejioa,
  vliq120mlFranklyMonkeyMetaUniverseFruitMix,
  vliq120mlFranklyMonkeyMetaUniverseIceApple,
  vliq120mlFranklyMonkeyMetaUniverseIceAppleShoria,
  vliq120mlFranklyMonkeyMetaUniverseIceStrawberry,
  vliq120mlFranklyMonkeyMetaUniverseMango,
  vliq120mlFranklyMonkeyMetaUniverseSaltedCaramel,
  vliq120mlFranklyMonkeyMetaUniverseStrawberryCheesecake,
  vliq120mlFranklyMonkeyMetaUniverseStrawberryKiwi,
  vliq120mlFranklyMonkeyMetaUniverseStrawberryRaf,
  vliq120mlFreezeBreezeBerryKiwiGrapefruit,
  vliq120mlFreezeBreezeBerryMix,
  vliq120mlFreezeBreezeBerryRaspberryPear,
  vliq120mlFreezeBreezeBlackHole,
  vliq120mlFreezeBreezeBlueberries,
  vliq120mlFreezeBreezeCherryJuice,
  vliq120mlFreezeBreezeCitrusPunch,
  vliq120mlFreezeBreezeCola,
  vliq120mlFreezeBreezeFanta,
  vliq120mlFreezeBreezeGrapeJuice,
  vliq120mlFreezeBreezeKiwiApple,
  vliq120mlFreezeBreezeLycheePineapple,
  vliq120mlFreezeBreezeMangoOrange,
  vliq120mlFreezeBreezeMangoPassionFruit,
  vliq120mlFreezeBreezePeachJuice,
  vliq120mlFreezeBreezePeachStrawberrySmoothie,
  vliq120mlFreezeBreezePineappleJuice,
  vliq120mlFreezeBreezeRootBeer,
  vliq120mlFreezeBreezeTropicalExplosion,
  vliq120mlFreezeBreezeWildBerries,
  vliq120mlFrostDrozdBlackberry,
  vliq120mlFrostDrozdBlueberry,
  vliq120mlFrostDrozdCactus,
  vliq120mlFrostDrozdCocountPassionPineapple,
  vliq120mlFrostDrozdGuavaLychee,
  vliq120mlFrostDrozdKiwiGrape,
  vliq120mlFrostDrozdLemon,
  vliq120mlFrostDrozdMango,
  vliq120mlFrostDrozdMangoPassionFruitSoda,
  vliq120mlFrostDrozdMelonApple,
  vliq120mlFrostDrozdMelonDragonFruit,
  vliq120mlFrostDrozdMelonSherbet,
  vliq120mlFrostDrozdPear,
  vliq120mlFrostDrozdPineappleSoda,
  vliq120mlFrostDrozdPineappleStrawberry,
  vliq120mlFrostDrozdPinkman,
  vliq120mlFrostDrozdTutiFruti,
  vliq120mlFrostDrozdWatermelon,
  vliq120mlHolodnoPesecAnanas,
  vliq120mlHolodnoPesecApple,
  vliq120mlHolodnoPesecCherry,
  vliq120mlHolodnoPesecCurrantPear,
  vliq120mlHolodnoPesecDrPepper,
  vliq120mlHolodnoPesecEnergyDrinkKiwi,
  vliq120mlHolodnoPesecGrape,
  vliq120mlHolodnoPesecGrapefruitBlueberries,
  vliq120mlHolodnoPesecGreenMango,
  vliq120mlHolodnoPesecMalina,
  vliq120mlHolodnoPesecOrange,
  vliq120mlHolodnoPesecPassionFruit,
  vliq120mlHolodnoPesecPeach,
  vliq120mlHolodnoPesecSpriteWithCucumber,
  vliq120mlHolodnoPesecWildStrawberry,
  vliq120mlMaxFlavorAperol,
  vliq120mlMaxFlavorApple,
  vliq120mlMaxFlavorBananaStrawberry,
  vliq120mlMaxFlavorBerriesMix,
  vliq120mlMaxFlavorBerriesWithMint,
  vliq120mlMaxFlavorBlueRaspberry,
  vliq120mlMaxFlavorCactus,
  vliq120mlMaxFlavorCarrot,
  vliq120mlMaxFlavorEnergyDrinkWithMango,
  vliq120mlMaxFlavorGrapeWithAloe,
  vliq120mlMaxFlavorGuava,
  vliq120mlMaxFlavorKiwi,
  vliq120mlMaxFlavorKiwiWithJasmine,
  vliq120mlMaxFlavorLemonadeStrawberryBasil,
  vliq120mlMaxFlavorLycheeWithTropicalFruits,
  vliq120mlMaxFlavorMarmalade,
  vliq120mlMaxFlavorMelon,
  vliq120mlMaxFlavorMintTickTock,
  vliq120mlMaxFlavorPeach,
  vliq120mlMaxFlavorPear,
  vliq120mlMaxFlavorPearApple,
  vliq120mlMaxFlavorPinaColada,
  vliq120mlMaxFlavorPineapple,
  vliq120mlMaxFlavorPineappleStrawberryLemongrass,
  vliq120mlMaxFlavorRaspberryLemon,
  vliq120mlMaxFlavorStrawberry,
  vliq120mlMaxFlavorStrawberryLemonMango,
  vliq120mlMaxFlavorSweetGrapefruit,
  vliq120mlMaxFlavorWatermelonLemonade,
  vliq120mlMaxFlavorYellowMangoRaspberry,
  vliq120mlShockApple,
  vliq120mlShockCherry,
  vliq120mlShockCranberries,
  vliq120mlShockCurrant,
  vliq120mlShockEnergy,
  vliq120mlShockKiwi,
  vliq120mlShockLemonPie,
  vliq120mlShockLychee,
  vliq120mlShockMango,
  vliq120mlShockMarmalade,
  vliq120mlShockMountainDew,
  vliq120mlShockPineappleLemon,
  vliq120mlShockRaspberry,
  vliq120mlShockSkittels,
  vliq120mlShockStrawberry,
} from "..";

export const VLIQ_LINES = {
  id: "vliq-lines",
  brand: "VLIQ",
  items: {
    thirtyML: [
      {
        id: 1,
        name: "BLIZZARD",
        goods: [
          {
            id: 1,
            image: vliq30mlBlizzardApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq30mlBlizzardCherry,
            name: "ВИШНЯ",
          },
          {
            id: 3,
            image: vliq30mlBlizzardCranberries,
            name: "КЛЮКВА",
          },
          {
            id: 4,
            image: vliq30mlBlizzardCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 5,
            image: vliq30mlBlizzardEnergyDrink,
            name: "ЭНЕРГЕТИК",
          },
          {
            id: 6,
            image: vliq30mlBlizzardKiwi,
            name: "КИВИ",
          },
          {
            id: 7,
            image: vliq30mlBlizzardLemonPie,
            name: "ЛЕМОННЫЙ ПИРОГ",
          },
          {
            id: 8,
            image: vliq30mlBlizzardLychee,
            name: "ЛИЧИ",
          },
          {
            id: 9,
            image: vliq30mlBlizzardMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq30mlBlizzardMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 11,
            image: vliq30mlBlizzardMountainDew,
            name: "МАУНТИН ДЬЮ",
          },
          {
            id: 12,
            image: vliq30mlBlizzardPineappleLemon,
            name: "АНАНАС ЛЕМОН",
          },
          {
            id: 13,
            image: vliq30mlBlizzardRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq30mlBlizzardSkittels,
            name: "СКИТТЛС",
          },
          {
            id: 15,
            image: vliq30mlBlizzardStrawberry,
            name: "КЛУБНИКА",
          },
        ],
      },
      {
        id: 2,
        name: "FATA MORGANA",
        goods: [
          {
            id: 1,
            image: vliq30mlFataMorganaBanana,
            name: "БАНАН",
          },
          {
            id: 2,
            image: vliq30mlFataMorganaCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 3,
            image: vliq30mlFataMorganaFanta,
            name: "ФАНТА",
          },
          {
            id: 4,
            image: vliq30mlFataMorganaLycheeStrawberry,
            name: "ЛИЧИ КЛУБНИКА",
          },
          {
            id: 5,
            image: vliq30mlFataMorganaMangoGuava,
            name: "МАНГО ГУАВА",
          },
          {
            id: 6,
            image: vliq30mlFataMorganaOrbitLime,
            name: "ОРБИТ ЛАЙМ",
          },
          {
            id: 7,
            image: vliq30mlFataMorganaPeachCinnabon,
            name: "ПЕРСИК СИННАБОН",
          },
          {
            id: 8,
            image: vliq30mlFataMorganaRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 9,
            image: vliq30mlFataMorganaStrawberryLiqurcie,
            name: "КЛУБНИЧНЫЙ ЛИКЕР",
          },
          {
            id: 10,
            image: vliq30mlFataMorganaStrawberryTea,
            name: "КЛУБНИЧНЫЙ ЧАЙ",
          },
        ],
      },
      {
        id: 3,
        name: "FRANKLY MONKEY BLACK",
        goods: [
          {
            id: 1,
            image: vliq30mlFranklyMonkeyBlackBlueberryJam,
            name: "ДЖЕМ ИЗ ГОЛУБИКИ",
          },
          {
            id: 2,
            image: vliq30mlFranklyMonkeyBlackBubbleGum,
            name: "ЖВАЧКА",
          },
          {
            id: 3,
            image: vliq30mlFranklyMonkeyBlackCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 4,
            image: vliq30mlFranklyMonkeyBlackGrapeIceCream,
            name: "ВИНОГРАД-МОРОЖЕНОЕ",
          },
          {
            id: 5,
            image: vliq30mlFranklyMonkeyBlackMultifruit,
            name: "МУЛЬТИФРУКТ",
          },
          {
            id: 6,
            image: vliq30mlFranklyMonkeyBlackNuts,
            name: "ОРЕХИ",
          },
          {
            id: 7,
            image: vliq30mlFranklyMonkeyBlackRaspberryLemon,
            name: "МАЛИНА ЛИМОН",
          },
          {
            id: 8,
            image: vliq30mlFranklyMonkeyBlackStrawberryKiwi,
            name: "КЛУБНИКА КИВИ",
          },
        ],
      },
      {
        id: 4,
        name: "FRANKLY MONKEY META UNIVERSE",
        goods: [
          {
            id: 1,
            image: vliq30mlFranklyMonkeyMetaUniverseBarberry,
            name: "БАРБАРИС",
          },
          {
            id: 2,
            image: vliq30mlFranklyMonkeyMetaUniverseBlueberryPorridge,
            name: "ЧЕРНИЧНАЯ КАША",
          },
          {
            id: 3,
            image: vliq30mlFranklyMonkeyMetaUniverseCactus,
            name: "КАКТУС",
          },
          {
            id: 4,
            image: vliq30mlFranklyMonkeyMetaUniverseDelicateYogurt,
            name: "ДЕЛИКАТНЫЙ ЙОГУРТ",
          },
          {
            id: 5,
            image: vliq30mlFranklyMonkeyMetaUniverseFeijoa,
            name: "ФЕЙХОА",
          },
          {
            id: 6,
            image: vliq30mlFranklyMonkeyMetaUniverseFruitMix,
            name: "ФРУКТОВЫЙ МИКС",
          },
          {
            id: 7,
            image: vliq30mlFranklyMonkeyMetaUniverseIceApple,
            name: "ЛЕДЯНОЕ ЯБЛОКО",
          },
          {
            id: 8,
            image: vliq30mlFranklyMonkeyMetaUniverseIceStrawberry,
            name: "ЛЕДЯНАЯ КЛУБНИКА",
          },
          {
            id: 9,
            image: vliq30mlFranklyMonkeyMetaUniverseMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq30mlFranklyMonkeyMetaUniverseSaltedCaramel,
            name: "СОЛЕНАЯ КАРАМЕЛЬ",
          },
          {
            id: 11,
            image: vliq30mlFranklyMonkeyMetaUniverseShoria,
            name: "ШОРИЯ",
          },
          {
            id: 12,
            image: vliq30mlFranklyMonkeyMetaUniverseStrawberryCheescake,
            name: "КЛУБНИЧНЫЙ ЧИЗКЕЙК",
          },
          {
            id: 13,
            image: vliq30mlFranklyMonkeyMetaUniverseStrawberryKiwi,
            name: "КЛУБНИЧНЫЙ КИВИ",
          },
          {
            id: 12,
            image: vliq30mlFranklyMonkeyMetaUniverseStrawberryRaf,
            name: "КЛУБНИЧНЫЙ РАФ",
          },
        ],
      },
      {
        id: 5,
        name: "FREEZE BREEZE",
        goods: [
          {
            id: 1,
            image: vliq30mlFreezeBreezeBerryMix,
            name: "ЯГОДНЫЙ МИКС",
          },
          {
            id: 2,
            image: vliq30mlFreezeBreezeBlackHole,
            name: "ЧЕРНАЯ ДЫРА",
          },
          {
            id: 3,
            image: vliq30mlFreezeBreezeBlueberry,
            name: "ЧЕРНИКА",
          },
          {
            id: 4,
            image: vliq30mlFreezeBreezeCherryJuice,
            name: "ВИШНЕВЫЙ СОК",
          },
          {
            id: 5,
            image: vliq30mlFreezeBreezeCitrusPunch,
            name: "ЦИТРУСОВЫЙ ПУНШ",
          },
          {
            id: 6,
            image: vliq30mlFreezeBreezeCola,
            name: "КОЛА",
          },
          {
            id: 7,
            image: vliq30mlFreezeBreezeFanta,
            name: "ФАНТА",
          },
          {
            id: 8,
            image: vliq30mlFreezeBreezeGrapeJuice,
            name: "ВИНОГРАДНЫЙ СОК",
          },
          {
            id: 9,
            image: vliq30mlFreezeBreezeKiwiApple,
            name: "КИВИ ЯБЛОКО",
          },
          {
            id: 10,
            image: vliq30mlFreezeBreezeKiwiGrapefruit,
            name: "КИВИ ГРЕЙПФРУТ",
          },
          {
            id: 11,
            image: vliq30mlFreezeBreezeLycheePineapple,
            name: "ЛИЧИ АНАНАС",
          },
          {
            id: 12,
            image: vliq30mlFreezeBreezeMangoOrange,
            name: "МАНГО АПЕЛЬСИН",
          },
          {
            id: 13,
            image: vliq30mlFreezeBreezeMangoPassionFruit,
            name: "МАНГО МАРАКУЙЯ",
          },
          {
            id: 14,
            image: vliq30mlFreezeBreezePeachApple,
            name: "ПЕРСИК ЯБЛОКО",
          },
          {
            id: 15,
            image: vliq30mlFreezeBreezePeachStrawberrySmoothe,
            name: "ПЕРСИК КЛУБНИКА СМУЗИ",
          },
          {
            id: 16,
            image: vliq30mlFreezeBreezePineappleJuice,
            name: "АНАНАСОВЫЙ СОК",
          },
          {
            id: 17,
            image: vliq30mlFreezeBreezeRaspberryPear,
            name: "МАЛИНА ГРУША",
          },
          {
            id: 18,
            image: vliq30mlFreezeBreezeRootBeer,
            name: "КОРНЕВОЙ МЕДВЕДЬ",
          },
          {
            id: 19,
            image: vliq30mlFreezeBreezeTropicalExplosion,
            name: "ТРОПИЧЕСКИЙ ВЗРЫВ",
          },
          {
            id: 20,
            image: vliq30mlFreezeBreezeWildBerries,
            name: "ДИКИЕ ЯГОДЫ",
          },
        ],
      },
      {
        id: 6,
        name: "FREEZE BREEZE SHOCK",
        goods: [
          {
            id: 1,
            image: vliq30mlFreezeBreezeShockApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq30mlFreezeBreezeShockCherry,
            name: "ВИШНЯ",
          },
          {
            id: 3,
            image: vliq30mlFreezeBreezeShockCranberries,
            name: "КЛЮКВА",
          },
          {
            id: 4,
            image: vliq30mlFreezeBreezeShockCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 5,
            image: vliq30mlFreezeBreezeShockEnergyDrink,
            name: "ЭНЕРГЕТИК",
          },
          {
            id: 6,
            image: vliq30mlFreezeBreezeShockKiwi,
            name: "КИВИ",
          },
          {
            id: 7,
            image: vliq30mlFreezeBreezeShockLemonPie,
            name: "ЛИМОННЫЙ ПИРОГ",
          },
          {
            id: 8,
            image: vliq30mlFreezeBreezeShockLychee,
            name: "ЛИЧИ",
          },
          {
            id: 9,
            image: vliq30mlFreezeBreezeShockMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq30mlFreezeBreezeShockMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 11,
            image: vliq30mlFreezeBreezeShockMountainDew,
            name: "МАУНТИН ДЬЮ",
          },
          {
            id: 12,
            image: vliq30mlFreezeBreezeShockPineappleLemon,
            name: "АНАНАС ЛИМОН",
          },
          {
            id: 13,
            image: vliq30mlFreezeBreezeShockRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq30mlFreezeBreezeShockSkittels,
            name: "СКИТТЛС",
          },
          {
            id: 15,
            image: vliq30mlFreezeBreezeShockStrawberry,
            name: "КЛУБНИКА",
          },
        ],
      },
      {
        id: 7,
        name: "FROST DROZD",
        goods: [
          {
            id: 1,
            image: vliq30mlFrostDrozdBlackberry,
            name: "ЕЖЕВИКА",
          },
          {
            id: 2,
            image: vliq30mlFrostDrozdBlueberry,
            name: "ЧЕРНИКА",
          },
          {
            id: 3,
            image: vliq30mlFrostDrozdCactus,
            name: "КАКТУС",
          },
          {
            id: 4,
            image: vliq30mlFrostDrozdCoconutPassionPineapple,
            name: "КОКОС МАРАКУЙЯ АНАНАС",
          },
          {
            id: 5,
            image: vliq30mlFrostDrozdDragonFruit,
            name: "ПИТАЙЯ",
          },
          {
            id: 6,
            image: vliq30mlFrostDrozdGuavaLychee,
            name: "ГУАВА ЛИЧИ",
          },
          {
            id: 7,
            image: vliq30mlFrostDrozdKiwiGrape,
            name: "КИВИ ВИНОГРАД",
          },
          {
            id: 8,
            image: vliq30mlFrostDrozdLemon,
            name: "ЛИМОН",
          },
          {
            id: 9,
            image: vliq30mlFrostDrozdMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq30mlFrostDrozdMangoPassionSoda,
            name: "МАНГО МАРАКУЙЯ СОДОВАЯ",
          },
          {
            id: 11,
            image: vliq30mlFrostDrozdMelonApple,
            name: "ДЫНЯ ЯБЛОКО",
          },
          {
            id: 12,
            image: vliq30mlFrostDrozdPear,
            name: "ГРУША",
          },
          {
            id: 13,
            image: vliq30mlFrostDrozdPineappleSoda,
            name: "АНАНАСОВАЯ СОДОВАЯ",
          },
          {
            id: 14,
            image: vliq30mlFrostDrozdPinkman,
            name: "ПИНКМАН",
          },
          {
            id: 15,
            image: vliq30mlFrostDrozdSherbet,
            name: "ШЕРБЕТ",
          },
          {
            id: 16,
            image: vliq30mlFrostDrozdStrawberryPineapple,
            name: "КЛУБНИКА АНАНАС",
          },
          {
            id: 17,
            image: vliq30mlFrostDrozdTuttiFruti,
            name: "ТУТТИ ФРУТИ",
          },
          {
            id: 18,
            image: vliq30mlFrostDrozdWatermelon,
            name: "АРБУЗ",
          },
        ],
      },
      {
        id: 8,
        name: "HOLODNO PESEC",
        goods: [
          {
            id: 1,
            image: vliq30mlHolodnoPesecApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq30mlHolodnoPesecBlueberries,
            name: "ЧЕРНИКА",
          },
          {
            id: 3,
            image: vliq30mlHolodnoPesecCherry,
            name: "ВИШНЯ",
          },
          {
            id: 4,
            image: vliq30mlHolodnoPesecCurrantPear,
            name: "СМОРОДИНА ГРУША",
          },
          {
            id: 5,
            image: vliq30mlHolodnoPesecDrPepper,
            name: "ДОКТОР ПЕППЕР",
          },
          {
            id: 6,
            image: vliq30mlHolodnoPesecEnergyDrinkKiwi,
            name: "ЭНЕРГЕТИК КИВИ",
          },
          {
            id: 7,
            image: vliq30mlHolodnoPesecGrape,
            name: "ВИНОГРАД",
          },
          {
            id: 8,
            image: vliq30mlHolodnoPesecGreenMango,
            name: "ЗЕЛЕНЫЙ МАНГО",
          },
          {
            id: 9,
            image: vliq30mlHolodnoPesecOrange,
            name: "АПЕЛЬСИН",
          },
          {
            id: 10,
            image: vliq30mlHolodnoPesecPassionFruit,
            name: "МАРАКУЙЯ",
          },
          {
            id: 11,
            image: vliq30mlHolodnoPesecPeach,
            name: "ПЕРСИК",
          },
          {
            id: 12,
            image: vliq30mlHolodnoPesecPineapple,
            name: "АНАНАС",
          },
          {
            id: 13,
            image: vliq30mlHolodnoPesecRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq30mlHolodnoPesecSpriteWithCucumber,
            name: "СПРАЙТ С ОГУРЦОМ",
          },
          {
            id: 15,
            image: vliq30mlHolodnoPesecWildStrawberry,
            name: "ДИКАЯ КЛУБНИКА",
          },
        ],
      },
      {
        id: 9,
        name: "LOOT",
        goods: [
          {
            id: 1,
            image: vliq30mlLootCherryYogurt,
            name: "ВИШНЯ ЙОГУРТ",
          },
          {
            id: 2,
            image: vliq30mlLootCinnamonApple,
            name: "КОРИЦА ЯБЛОКО ",
          },
          {
            id: 3,
            image: vliq30mlLootCrazyWatermelon,
            name: "СУМАСШЕДШАЯ ДЫНЯ",
          },
          {
            id: 4,
            image: vliq30mlLootCurrantRaspberry,
            name: "СМОРОДИНА МАЛИНА",
          },
          {
            id: 5,
            image: vliq30mlLootFejioa,
            name: "ФЕЙХОА",
          },
          {
            id: 6,
            image: vliq30mlLootFunnyRaspberry,
            name: "ВЕСЕЛАЯ МАЛИНА",
          },
          {
            id: 7,
            image: vliq30mlLootKiwi,
            name: "КИВИ",
          },
          {
            id: 8,
            image: vliq30mlLootLimeApple,
            name: "ЛАЙМ ЯБЛОКО",
          },
          {
            id: 9,
            image: vliq30mlLootPear,
            name: "ГРУША",
          },
          {
            id: 10,
            image: vliq30mlLootPomegranateApple,
            name: "ГРАНАТ ЯБЛОКО",
          },
          {
            id: 11,
            image: vliq30mlLootRareTropics,
            name: "РЕДКИЕ ТРОПИКИ",
          },
          {
            id: 12,
            image: vliq30mlLootStrawberry,
            name: "КЛУБНИКА",
          },
          {
            id: 13,
            image: vliq30mlLootSuperPunch,
            name: "СУПЕР ПУНШ",
          },
        ],
      },
      {
        id: 10,
        name: "LOOT ICE",
        goods: [
          {
            id: 1,
            image: vliq30mlLootIceAmazingMojito,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 2,
            image: vliq30mlLootIceCitrusFruit,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 3,
            image: vliq30mlLootIceGreenApple,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 4,
            image: vliq30mlLootIceKiwiMango,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 5,
            image: vliq30mlLootIceLimeCactus,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 6,
            image: vliq30mlLootIceMangoApple,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 7,
            image: vliq30mlLootIceMelissa,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 8,
            image: vliq30mlLootIceOrangePassion,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 9,
            image: vliq30mlLootIcePeachPassion,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 10,
            image: vliq30mlLootIcePineappleLychee,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 11,
            image: vliq30mlLootIceRareBerries,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 12,
            image: vliq30mlLootIceStrawberryCherry,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 13,
            image: vliq30mlLootIceStrawberryLemon,
            name: "ДИКАЯ КЛУБНИКА",
          },
          {
            id: 14,
            image: vliq30mlLootIceWatermelonMandarin,
            name: "ДИКАЯ КЛУБНИКА",
          },
        ],
      },
      {
        id: 11,
        name: "MAX FLAVOR",
        goods: [
          {
            id: 1,
            image: vliq30mlMaxFlavorAperol,
            name: "АПЕРОЛЬ",
          },
          {
            id: 2,
            image: vliq30mlMaxFlavorApple,
            name: "ЯБЛОКО",
          },
          {
            id: 3,
            image: vliq30mlMaxFlavorApplePear,
            name: "ЯБЛОКО ГРУША",
          },
          {
            id: 4,
            image: vliq30mlMaxFlavorBerriesWithMint,
            name: "ЯГОДЫ С МЯТОЙ",
          },
          {
            id: 5,
            image: vliq30mlMaxFlavorBerryYogurt,
            name: "ЯГОДНЫЙ ЙОГУРТ",
          },
          {
            id: 6,
            image: vliq30mlMaxFlavorBlueRaspberry,
            name: "ГОЛУБАЯ МАЛИНА",
          },
          {
            id: 7,
            image: vliq30mlMaxFlavorCactus,
            name: "КАКТУС",
          },
          {
            id: 8,
            image: vliq30mlMaxFlavorCarrot,
            name: "МОРКОВЬ",
          },
          {
            id: 9,
            image: vliq30mlMaxFlavorEnergyDrinkWithMango,
            name: "ЭНЕРГЕТИК С МАНГО",
          },
          {
            id: 10,
            image: vliq30mlMaxFlavorGrapeWithAloe,
            name: "ВИНОГРАД С АЛОЭ",
          },
          {
            id: 11,
            image: vliq30mlMaxFlavorGuava,
            name: "ГУАВА",
          },
          {
            id: 12,
            image: vliq30mlMaxFlavorKiwi,
            name: "КИВИ",
          },
          {
            id: 13,
            image: vliq30mlMaxFlavorLemonRaspberry,
            name: "ЛИМОН МАЛИНА",
          },
          {
            id: 14,
            image: vliq30mlMaxFlavorLemonadeStrawberryBasil,
            name: "ЛИМОНАД КЛУБНИКА БАЗИЛИК",
          },
          {
            id: 15,
            image: vliq30mlMaxFlavorLycheeWithTropicalFruits,
            name: "ЛИЧИ С ТРОПИЧЕСКИМИ ФРУКТАМИ",
          },
          {
            id: 16,
            image: vliq30mlMaxFlavorMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 17,
            image: vliq30mlMaxFlavorMelon,
            name: "ДЫНЯ",
          },
          {
            id: 18,
            image: vliq30mlMaxFlavorMintTickTock,
            name: "МЯТНЫЙ ТИК ТАК",
          },
          {
            id: 19,
            image: vliq30mlMaxFlavorPeach,
            name: "ПЕРСИК",
          },
          {
            id: 20,
            image: vliq30mlMaxFlavorPear,
            name: "ГРУША",
          },
          {
            id: 21,
            image: vliq30mlMaxFlavorPinaColada,
            name: "ПИНА КОЛАДА",
          },
          {
            id: 22,
            image: vliq30mlMaxFlavorPineapple,
            name: "АНАНАС",
          },
          {
            id: 23,
            image: vliq30mlMaxFlavorRoseWithJasmine,
            name: "РОЗА С ЖАСМИНОМ",
          },
          {
            id: 24,
            image: vliq30mlMaxFlavorStrawberry,
            name: "КЛУБНИКА",
          },
          {
            id: 25,
            image: vliq30mlMaxFlavorStrawberryBanana,
            name: "КЛУБНИКА БАНАН",
          },
          {
            id: 26,
            image: vliq30mlMaxFlavorStrawberryLemonMango,
            name: "КЛУБНИКА ЛИМОН МАНГО",
          },
          {
            id: 27,
            image: vliq30mlMaxFlavorStrawberryPineappleLemongrass,
            name: "КЛУБНИКА АНАНАС ЛЕМОНГРАСС",
          },
          {
            id: 28,
            image: vliq30mlMaxFlavorSweetGrapefruit,
            name: "СЛАДКИЙ ГРЕЙПФРУТ",
          },
          {
            id: 29,
            image: vliq30mlMaxFlavorWatermelonLemonade,
            name: "АРБУЗНЫЙ ЛИМОНАД",
          },
          {
            id: 30,
            image: vliq30mlMaxFlavorYellowMangoWithRaspberries,
            name: "МАНГО С МАЛИНОЙ",
          },
        ],
      },
    ],
    oneHundredAndTwentyML: [
      {
        id: 1,
        name: "BLIZZARD",
        goods: [
          {
            id: 1,
            image: vliq120mlBlizzardApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq120mlBlizzardCherry,
            name: "ВИШНЯ",
          },
          {
            id: 3,
            image: vliq120mlBlizzardCranberries,
            name: "КЛЮКВА",
          },
          {
            id: 4,
            image: vliq120mlBlizzardCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 5,
            image: vliq120mlBlizzardEnergyDrink,
            name: "ЭНЕРГЕТИК",
          },
          {
            id: 6,
            image: vliq120mlBlizzardKiwi,
            name: "КИВИ",
          },
          {
            id: 7,
            image: vliq120mlBlizzardLemonPie,
            name: "ЛЕМОННЫЙ ПИРОГ",
          },
          {
            id: 8,
            image: vliq120mlBlizzardLychee,
            name: "ЛИЧИ",
          },
          {
            id: 9,
            image: vliq120mlBlizzardMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq120mlBlizzardMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 11,
            image: vliq120mlBlizzardMountainDew,
            name: "МАУНТИН ДЬЮ",
          },
          {
            id: 12,
            image: vliq120mlBlizzardPineappleLemon,
            name: "АНАНАС ЛЕМОН",
          },
          {
            id: 13,
            image: vliq120mlBlizzardRasberry,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq120mlBlizzardSkittels,
            name: "СКИТТЛС",
          },
          {
            id: 15,
            image: vliq120mlBlizzardStrawberry,
            name: "КЛУБНИКА",
          },
        ],
      },
      {
        id: 2,
        name: "FATA MORGANA",
        goods: [
          {
            id: 1,
            image: vliq120mlFataMorganaBanana,
            name: "БАНАН",
          },
          {
            id: 2,
            image: vliq120mlFataMorganaCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 3,
            image: vliq120mlFataMorganaFanta,
            name: "ФАНТА",
          },
          {
            id: 4,
            image: vliq120mlFataMorganaLycheeStrawberry,
            name: "ЛИЧИ КЛУБНИКА",
          },
          {
            id: 5,
            image: vliq120mlFataMorganaMangoGuava,
            name: "МАНГО ГУАВА",
          },
          {
            id: 6,
            image: vliq120mlFataMorganaOrbitLime,
            name: "ОРБИТ ЛАЙМ",
          },
          {
            id: 7,
            image: vliq120mlFataMorganaPeachCinnamon,
            name: "ПЕРСИК СИННАБОН",
          },
          {
            id: 8,
            image: vliq120mlFataMorganaRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 9,
            image: vliq120mlFataMorganaStrawberryLiquorice,
            name: "КЛУБНИЧНЫЙ ЛИКЕР",
          },
          {
            id: 10,
            image: vliq120mlFataMorganaStrawberryTea,
            name: "КЛУБНИЧНЫЙ ЧАЙ",
          },
        ],
      },
      {
        id: 3,
        name: "FRANKLY MONKEY BLACK",
        goods: [
          {
            id: 1,
            image: vliq120mlFranklyMonkeyBlackBlueberryJam,
            name: "ДЖЕМ ИЗ ГОЛУБИКИ",
          },
          {
            id: 2,
            image: vliq120mlFranklyMonkeyBlackBubbleGum,
            name: "ЖВАЧКА",
          },
          {
            id: 3,
            image: vliq120mlFranklyMonkeyBlackCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 4,
            image: vliq120mlFranklyMonkeyBlackCrapeIceCream,
            name: "ВИНОГРАД-МОРОЖЕНОЕ",
          },
          {
            id: 5,
            image: vliq120mlFranklyMonkeyBlackMultifruit,
            name: "МУЛЬТИФРУКТ",
          },
          {
            id: 6,
            image: vliq120mlFranklyMonkeyBlackNuts,
            name: "ОРЕХИ",
          },
          {
            id: 7,
            image: vliq120mlFranklyMonkeyBlackRaspberryLemon,
            name: "МАЛИНА ЛИМОН",
          },
          {
            id: 8,
            image: vliq120mlFranklyMonkeyBlackKiwiStrawberry,
            name: "КЛУБНИКА КИВИ",
          },
        ],
      },
      {
        id: 4,
        name: "FRANKLY MONKEY META UNIVERSE",
        goods: [
          {
            id: 1,
            image: vliq120mlFranklyMonkeyMetaUniverseBarberry,
            name: "БАРБАРИС",
          },
          {
            id: 2,
            image: vliq120mlFranklyMonkeyMetaUniverseBlueberryPorrige,
            name: "ЧЕРНИЧНАЯ КАША",
          },
          {
            id: 3,
            image: vliq120mlFranklyMonkeyMetaUniverseCactus,
            name: "КАКТУС",
          },
          {
            id: 4,
            image: vliq120mlFranklyMonkeyMetaUniverseDelicateYogurt,
            name: "ДЕЛИКАТНЫЙ ЙОГУРТ",
          },
          {
            id: 5,
            image: vliq120mlFranklyMonkeyMetaUniverseFejioa,
            name: "ФЕЙХОА",
          },
          {
            id: 6,
            image: vliq120mlFranklyMonkeyMetaUniverseFruitMix,
            name: "ФРУКТОВЫЙ МИКС",
          },
          {
            id: 7,
            image: vliq120mlFranklyMonkeyMetaUniverseIceApple,
            name: "ЛЕДЯНОЕ ЯБЛОКО",
          },
          {
            id: 8,
            image: vliq120mlFranklyMonkeyMetaUniverseIceStrawberry,
            name: "ЛЕДЯНАЯ КЛУБНИКА",
          },
          {
            id: 9,
            image: vliq120mlFranklyMonkeyMetaUniverseMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq120mlFranklyMonkeyMetaUniverseSaltedCaramel,
            name: "СОЛЕНАЯ КАРАМЕЛЬ",
          },
          {
            id: 11,
            image: vliq120mlFranklyMonkeyMetaUniverseIceAppleShoria,
            name: "ШОРИЯ",
          },
          {
            id: 12,
            image: vliq120mlFranklyMonkeyMetaUniverseStrawberryCheesecake,
            name: "КЛУБНИЧНЫЙ ЧИЗКЕЙК",
          },
          {
            id: 13,
            image: vliq120mlFranklyMonkeyMetaUniverseStrawberryKiwi,
            name: "КЛУБНИЧНЫЙ КИВИ",
          },
          {
            id: 12,
            image: vliq120mlFranklyMonkeyMetaUniverseStrawberryRaf,
            name: "КЛУБНИЧНЫЙ РАФ",
          },
        ],
      },
      {
        id: 5,
        name: "FREEZE BREEZE",
        goods: [
          {
            id: 1,
            image: vliq120mlFreezeBreezeBerryMix,
            name: "ЯГОДНЫЙ МИКС",
          },
          {
            id: 2,
            image: vliq120mlFreezeBreezeBlackHole,
            name: "ЧЕРНАЯ ДЫРА",
          },
          {
            id: 3,
            image: vliq120mlFreezeBreezeBlueberries,
            name: "ЧЕРНИКА",
          },
          {
            id: 4,
            image: vliq120mlFreezeBreezeCherryJuice,
            name: "ВИШНЕВЫЙ СОК",
          },
          {
            id: 5,
            image: vliq120mlFreezeBreezeCitrusPunch,
            name: "ЦИТРУСОВЫЙ ПУНШ",
          },
          {
            id: 6,
            image: vliq120mlFreezeBreezeCola,
            name: "КОЛА",
          },
          {
            id: 7,
            image: vliq120mlFreezeBreezeFanta,
            name: "ФАНТА",
          },
          {
            id: 8,
            image: vliq120mlFreezeBreezeGrapeJuice,
            name: "ВИНОГРАДНЫЙ СОК",
          },
          {
            id: 9,
            image: vliq120mlFreezeBreezeKiwiApple,
            name: "КИВИ ЯБЛОКО",
          },
          {
            id: 10,
            image: vliq120mlFreezeBreezeBerryKiwiGrapefruit,
            name: "КИВИ ГРЕЙПФРУТ",
          },
          {
            id: 11,
            image: vliq120mlFreezeBreezeLycheePineapple,
            name: "ЛИЧИ АНАНАС",
          },
          {
            id: 12,
            image: vliq120mlFreezeBreezeMangoOrange,
            name: "МАНГО АПЕЛЬСИН",
          },
          {
            id: 13,
            image: vliq120mlFreezeBreezeMangoPassionFruit,
            name: "МАНГО МАРАКУЙЯ",
          },
          {
            id: 14,
            image: vliq120mlFreezeBreezeBerryKiwiGrapefruit,
            name: "ПЕРСИК ЯБЛОКО",
          },
          {
            id: 15,
            image: vliq120mlFreezeBreezePeachStrawberrySmoothie,
            name: "ПЕРСИК КЛУБНИКА СМУЗИ",
          },
          {
            id: 16,
            image: vliq120mlFreezeBreezePineappleJuice,
            name: "АНАНАСОВЫЙ СОК",
          },
          {
            id: 17,
            image: vliq120mlFreezeBreezeBerryRaspberryPear,
            name: "МАЛИНА ГРУША",
          },
          {
            id: 18,
            image: vliq120mlFreezeBreezeRootBeer,
            name: "КОРНЕВОЙ МЕДВЕДЬ",
          },
          {
            id: 19,
            image: vliq120mlFreezeBreezeTropicalExplosion,
            name: "ТРОПИЧЕСКИЙ ВЗРЫВ",
          },
          {
            id: 20,
            image: vliq120mlFreezeBreezeWildBerries,
            name: "ДИКИЕ ЯГОДЫ",
          },
          {
            id: 21,
            image: vliq120mlFreezeBreezePeachJuice,
          },
        ],
      },
      {
        id: 6,
        name: "FROST DROZD",
        goods: [
          {
            id: 1,
            image: vliq120mlFrostDrozdBlackberry,
            name: "ЕЖЕВИКА",
          },
          {
            id: 2,
            image: vliq120mlFrostDrozdBlueberry,
            name: "ЧЕРНИКА",
          },
          {
            id: 3,
            image: vliq120mlFrostDrozdCactus,
            name: "КАКТУС",
          },
          {
            id: 4,
            image: vliq120mlFrostDrozdCocountPassionPineapple,
            name: "КОКОС МАРАКУЙЯ АНАНАС",
          },
          {
            id: 5,
            image: vliq120mlFrostDrozdMelonDragonFruit,
            name: "ПИТАЙЯ",
          },
          {
            id: 6,
            image: vliq120mlFrostDrozdGuavaLychee,
            name: "ГУАВА ЛИЧИ",
          },
          {
            id: 7,
            image: vliq120mlFrostDrozdKiwiGrape,
            name: "КИВИ ВИНОГРАД",
          },
          {
            id: 8,
            image: vliq120mlFrostDrozdLemon,
            name: "ЛИМОН",
          },
          {
            id: 9,
            image: vliq120mlFrostDrozdMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq120mlFrostDrozdMangoPassionFruitSoda,
            name: "МАНГО МАРАКУЙЯ СОДОВАЯ",
          },
          {
            id: 11,
            image: vliq120mlFrostDrozdMelonApple,
            name: "ДЫНЯ ЯБЛОКО",
          },
          {
            id: 12,
            image: vliq120mlFrostDrozdPear,
            name: "ГРУША",
          },
          {
            id: 13,
            image: vliq120mlFrostDrozdPineappleSoda,
            name: "АНАНАСОВАЯ СОДОВАЯ",
          },
          {
            id: 14,
            image: vliq120mlFrostDrozdPinkman,
            name: "ПИНКМАН",
          },
          {
            id: 15,
            image: vliq120mlFrostDrozdMelonSherbet,
            name: "ШЕРБЕТ",
          },
          {
            id: 16,
            image: vliq120mlFrostDrozdPineappleStrawberry,
            name: "КЛУБНИКА АНАНАС",
          },
          {
            id: 17,
            image: vliq120mlFrostDrozdTutiFruti,
            name: "ТУТТИ ФРУТИ",
          },
          {
            id: 18,
            image: vliq120mlFrostDrozdWatermelon,
            name: "АРБУЗ",
          },
        ],
      },
      {
        id: 7,
        name: "HOLODNO PESEC",
        goods: [
          {
            id: 1,
            image: vliq120mlHolodnoPesecApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq120mlHolodnoPesecGrapefruitBlueberries,
            name: "ГРЕЙПФРУТ ЧЕРНИКА",
          },
          {
            id: 3,
            image: vliq120mlHolodnoPesecCherry,
            name: "ВИШНЯ",
          },
          {
            id: 4,
            image: vliq120mlHolodnoPesecCurrantPear,
            name: "СМОРОДИНА ГРУША",
          },
          {
            id: 5,
            image: vliq120mlHolodnoPesecDrPepper,
            name: "ДОКТОР ПЕППЕР",
          },
          {
            id: 6,
            image: vliq120mlHolodnoPesecEnergyDrinkKiwi,
            name: "ЭНЕРГЕТИК КИВИ",
          },
          {
            id: 7,
            image: vliq120mlHolodnoPesecGrape,
            name: "ВИНОГРАД",
          },
          {
            id: 8,
            image: vliq120mlHolodnoPesecGreenMango,
            name: "ЗЕЛЕНЫЙ МАНГО",
          },
          {
            id: 9,
            image: vliq120mlHolodnoPesecOrange,
            name: "АПЕЛЬСИН",
          },
          {
            id: 10,
            image: vliq120mlHolodnoPesecPassionFruit,
            name: "МАРАКУЙЯ",
          },
          {
            id: 11,
            image: vliq120mlHolodnoPesecPeach,
            name: "ПЕРСИК",
          },
          {
            id: 12,
            image: vliq120mlHolodnoPesecAnanas,
            name: "АНАНАС",
          },
          {
            id: 13,
            image: vliq120mlHolodnoPesecMalina,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq120mlHolodnoPesecSpriteWithCucumber,
            name: "СПРАЙТ С ОГУРЦОМ",
          },
          {
            id: 15,
            image: vliq120mlHolodnoPesecWildStrawberry,
            name: "ДИКАЯ КЛУБНИКА",
          },
        ],
      },
      {
        id: 8,
        name: "MAX FLAVOR",
        goods: [
          {
            id: 1,
            image: vliq120mlMaxFlavorAperol,
            name: "АПЕРОЛЬ",
          },
          {
            id: 2,
            image: vliq120mlMaxFlavorApple,
            name: "ЯБЛОКО",
          },
          {
            id: 4,
            image: vliq120mlMaxFlavorBerriesWithMint,
            name: "ЯГОДЫ С МЯТОЙ",
          },
          {
            id: 5,
            image: vliq120mlMaxFlavorBerriesMix,
            name: "ЯГОДНЫЙ МИКС",
          },
          {
            id: 6,
            image: vliq120mlMaxFlavorBlueRaspberry,
            name: "ГОЛУБАЯ МАЛИНА",
          },
          {
            id: 7,
            image: vliq120mlMaxFlavorCactus,
            name: "КАКТУС",
          },
          {
            id: 8,
            image: vliq120mlMaxFlavorCarrot,
            name: "МОРКОВЬ",
          },
          {
            id: 9,
            image: vliq120mlMaxFlavorEnergyDrinkWithMango,
            name: "ЭНЕРГЕТИК С МАНГО",
          },
          {
            id: 10,
            image: vliq120mlMaxFlavorGrapeWithAloe,
            name: "ВИНОГРАД С АЛОЭ",
          },
          {
            id: 11,
            image: vliq120mlMaxFlavorGuava,
            name: "ГУАВА",
          },
          {
            id: 12,
            image: vliq120mlMaxFlavorKiwi,
            name: "КИВИ",
          },
          {
            id: 13,
            image: vliq120mlMaxFlavorBananaStrawberry,
            name: "БАНАН КЛУБНИКА",
          },
          {
            id: 14,
            image: vliq120mlMaxFlavorLemonadeStrawberryBasil,
            name: "ЛИМОНАД КЛУБНИКА БАЗИЛИК",
          },
          {
            id: 15,
            image: vliq120mlMaxFlavorLycheeWithTropicalFruits,
            name: "ЛИЧИ С ТРОПИЧЕСКИМИ ФРУКТАМИ",
          },
          {
            id: 16,
            image: vliq120mlMaxFlavorMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 17,
            image: vliq120mlMaxFlavorMelon,
            name: "ДЫНЯ",
          },
          {
            id: 18,
            image: vliq120mlMaxFlavorMintTickTock,
            name: "МЯТНЫЙ ТИК ТАК",
          },
          {
            id: 19,
            image: vliq120mlMaxFlavorPeach,
            name: "ПЕРСИК",
          },
          {
            id: 20,
            image: vliq120mlMaxFlavorPear,
            name: "ГРУША",
          },
          {
            id: 21,
            image: vliq120mlMaxFlavorPinaColada,
            name: "ПИНА КОЛАДА",
          },
          {
            id: 22,
            image: vliq120mlMaxFlavorPineapple,
            name: "АНАНАС",
          },
          {
            id: 23,
            image: vliq120mlMaxFlavorKiwiWithJasmine,
            name: "РОЗА С ЖАСМИНОМ",
          },
          {
            id: 24,
            image: vliq120mlMaxFlavorStrawberry,
            name: "КЛУБНИКА",
          },
          {
            id: 25,
            image: vliq120mlMaxFlavorPearApple,
            name: "ГРУША ЯБЛОКО",
          },
          {
            id: 26,
            image: vliq120mlMaxFlavorStrawberryLemonMango,
            name: "КЛУБНИКА ЛИМОН МАНГО",
          },
          {
            id: 27,
            image: vliq120mlMaxFlavorPineappleStrawberryLemongrass,
            name: "КЛУБНИКА АНАНАС ЛЕМОНГРАСС",
          },
          {
            id: 28,
            image: vliq120mlMaxFlavorSweetGrapefruit,
            name: "СЛАДКИЙ ГРЕЙПФРУТ",
          },
          {
            id: 29,
            image: vliq120mlMaxFlavorWatermelonLemonade,
            name: "АРБУЗНЫЙ ЛИМОНАД",
          },
          {
            id: 30,
            image: vliq120mlMaxFlavorYellowMangoRaspberry,
            name: "МАНГО С МАЛИНОЙ",
          },
          {
            id: 31,
            image: vliq120mlMaxFlavorRaspberryLemon,
            name: "МАЛИНА ЛИМОН",
          },
        ],
      },
      {
        id: 9,
        name: "SHOCK",
        goods: [
          {
            id: 1,
            image: vliq120mlShockApple,
            name: "ЯБЛОКО",
          },
          {
            id: 2,
            image: vliq120mlShockCherry,
            name: "ВИШНЯ",
          },
          {
            id: 3,
            image: vliq120mlShockCranberries,
            name: "КЛЮКВА",
          },
          {
            id: 4,
            image: vliq120mlShockCurrant,
            name: "СМОРОДИНА",
          },
          {
            id: 5,
            image: vliq120mlShockEnergy,
            name: "ЭНЕРГЕТИК",
          },
          {
            id: 6,
            image: vliq120mlShockKiwi,
            name: "КИВИ",
          },
          {
            id: 7,
            image: vliq120mlShockLemonPie,
            name: "ЛИМОННЫЙ ПИРОГ",
          },
          {
            id: 8,
            image: vliq120mlShockLychee,
            name: "ЛИЧИ",
          },
          {
            id: 9,
            image: vliq120mlShockMango,
            name: "МАНГО",
          },
          {
            id: 10,
            image: vliq120mlShockMarmalade,
            name: "МАРМЕЛАД",
          },
          {
            id: 11,
            image: vliq120mlShockMountainDew,
            name: "МАУНТИН ДЬЮ",
          },
          {
            id: 12,
            image: vliq120mlShockPineappleLemon,
            name: "АНАНАС ЛИМОН",
          },
          {
            id: 13,
            image: vliq120mlShockRaspberry,
            name: "МАЛИНА",
          },
          {
            id: 14,
            image: vliq120mlShockSkittels,
            name: "СКИТТЛС",
          },
          {
            id: 15,
            image: vliq120mlShockStrawberry,
            name: "КЛУБНИКА",
          },
        ],
      },
    ],
  },
};
